export const EventsData = [
    {
        id:1,
        name: 'Antanines',
        location: 'Krekenava',
        category: 'sports',
        price: '10',
        startEventDateTime: '2022-07-19 20:20',
        endEventDateTime: '2022-07-19 20:20',
        description: 'Bus labai smagu',
    },
    {
        id:2,
        name: 'Antanines',
        location: 'Krekenava',
        category: 'sports',
        price: '10',
        startEventDateTime: '2022-07-19 20:20',
        endEventDateTime: '2022-07-19 20:20',
        description: 'Bus labai smagu',
    },
    {
        id:3,
        name: 'Antanines',
        location: 'Krekenava',
        category: 'sports',
        price: '10',
        startEventDateTime: '2022-07-19 20:20',
        endEventDateTime: '2022-07-19 20:20',
        description: 'Bus labai smagu',
    },
    {
        id:4,
        name: 'Antanines',
        location: 'Krekenava',
        category: 'sports',
        price: '10',
        startEventDateTime: '2022-07-19 20:20',
        endEventDateTime: '2022-07-19 20:20',
        description: 'Bus labai smagu',
    },
    {
        id:5,
        name: 'Antanines',
        location: 'Krekenava',
        category: 'sports',
        price: '10',
        startEventDateTime: '2022-07-19 20:20',
        endEventDateTime: '2022-07-19 20:20',
        description: 'Bus labai smagu',
    },
    {
        id:6,
        name: 'Antanines',
        location: 'Krekenava',
        category: 'sports',
        price: '10',
        startEventDateTime: '2022-07-19 20:20',
        endEventDateTime: '2022-07-19 20:20',
        description: 'Bus labai smagu',
    },
];